# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: start
        run: 
          echo build page start, ready to setup Node
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: CheckOut DarkLight
        env:
          GITHUBTOKEN: ${{secrets.BLOG_DEMO_TOKEN}}
        run: |
          git clone https://github.com/DarkLight-Long/DarkLight.git
          echo ${GITHUBTOKEN}
          echo ${{ secrets.GITHUB_TOKEN }}
          pwd
          ls
      - name: Checkout blog-demo
        uses: actions/checkout@v2.3.5
        with: 
          repository: DarkLight-Long/blog-demo
          ref: dev
          path: ./blog-demo
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false
          fetch-depth: 0
      - name: Install Dependencies
        run: |
          cd ./DarkLight
          pwd
          ls
          npm install
          npm run build --if-present
          ls
      - name: MV dist to blog-demo
        run: |
          cd ./DarkLight
          /bin/cp -rf ./dist/* ../blog-demo
          cd ../blog-demo
          pwd
          ls
      - name: push to blog-demo
        run: |
          cd ./blog-demo
          pwd
          ls -a
          time1=$(date)
          git config --global user.name "DarkLight-Long"
          git config --global user.email "854590394@qq.com"
          git pull origin dev -f
          git add ./*
          git commit -m "${time1} action auto"
#        git push https://DarkLight-Long:${GITHUBTOKEN}@github.com/DarkLight-Long/blog-demo.git
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.BLOG_DEMO_TOKEN}}
          directory: ./blog-demo
          branch: dev
          force: true
      - name: end
        run: |
          echo successfully


